version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: uniandesIOT1234*
      POSTGRES_USER: dbadmin
      POSTGRES_DB: iot_data
  web:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db